### ISSUE TITLE
Viewportsize parameter is ignored

### ISSUE THREAD

**Issue by DarthMax** [superbrothers/capturejs#20]
I have discovered that some situations the --viewportsize option is ignored. For example if I run

```bash
capturejs --uri http://www.fosspatents.com/ \ 
            --viewportsize 1400x1000 \
            --output 'fosspatents.com.png'
```

all I get is a pretty large website. Maybe I get the meaning of this parameter wrong but I would expect that all the content that is not in the viewport is cut off.

**Comment by hilios** [comment]
I had the same issue, but the problem is not the `viewportSize` parameter and the lack of the `clipRect` I will submit a PR with the fix

**Comment by hilios** [comment]
Check-it out my PR #21

**Comment by DarthMax** [comment]
Nice! :thumbsup:
